#!/bin/sh
dots_dir="$HOME/.dotfiles"
config_dir="$HOME/.config"

if [ ! -d "$config_dir" ]; then
    mkdir $config_dir
fi

ln -sfv "$dots_dir/.profile" "$HOME"
ln -sfv "$dots_dir/.zprofile" "$HOME"
ln -sfv "$dots_dir/.zshrc" "$HOME"
ln -sfv "$dots_dir/.bashrc" "$HOME"
ln -sfv "$dots_dir/.i3" "$HOME"
ln -sfv "$dots_dir/.inputrc" "$HOME"
ln -sfv "$dots_dir/.pentadactylrc" "$HOME"
ln -sfv "$dots_dir/.vimrc" "$HOME"
ln -sfv "$dots_dir/.xinitrc" "$HOME"
ln -sfv "$dots_dir/.Xresources" "$HOME"
ln -sfv "$dots_dir/.Xmodmap" "$HOME"
ln -sfv "$dots_dir/.tmux.conf" "$HOME"
ln -sfv "$dots_dir/.ncmpcpp" "$HOME"
ln -sfv "$dots_dir/termite" "$config_dir"
ln -sfv "$dots_dir/zathura" "$config_dir"
